import FooterNav from '@/Components/common/FooterNav'
import NavBar from '@/Components/common/NavBar'
import Clients from '@/Components/home/Clients'
import FAQSection from '@/Components/home/FAQSection'
import HeroSection from '@/Components/home/HeroSection'
import HowToSetup from '@/Components/home/HowToSetup'
import Integrations from '@/Components/home/Integration'
import PricingSection from '@/Components/home/PricingSection'
import ReviewsCarousel from '@/Components/home/Reviews'
import SetUPTime from '@/Components/home/SetUPTime'
import TryIt from '@/Components/home/TryIt'
import Head from 'next/head'


export default function Home() {
  return (
    <>
      <Head>
        <title>UhuruChat</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <NavBar />
        <HeroSection />
        <SetUPTime />
        <Clients />
        <HowToSetup />
        <TryIt />
        <ReviewsCarousel />
        <Integrations />
        <FAQSection />
        <PricingSection />
        <FooterNav />
      </main>
    </>
  )
}
