import FooterNav from '@/Components/common/FooterNav'
import ProductSiteNav from '@/Components/common/ProductSiteNav'
import WebsiteNav from '@/Components/common/WebsiteNav'
import ContactUs from '@/Components/home/ContactUs'
import FAQSection from '@/Components/home/FAQSection'
import HeroSection from '@/Components/home/HeroSection'
import HowToSetup from '@/Components/home/HowToSetup'
import Integrations from '@/Components/home/Integration'
import PricingSection from '@/Components/home/PricingSection'
import ReviewsCarousel from '@/Components/home/Reviews'
import SetUPTime from '@/Components/home/SetUPTime'
import TabSwitcher from '@/Components/home/TabPannel'
import TryIt from '@/Components/home/TryIt'
import Head from 'next/head'


export default function Home() {
  return (
    <>
      <Head>
        <title>UhuruChat</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="https://uhurutek.com/assets/img/favicon.png" />
      </Head>
      <main>
        <WebsiteNav />
        <ProductSiteNav />
        <HeroSection />
        <SetUPTime />
        <TabSwitcher />
        <HowToSetup />
        <TryIt />
        <ReviewsCarousel />
        <Integrations />
        <FAQSection />
        <PricingSection />
        <ContactUs />
        <FooterNav />
      </main>
    </>
  )
}
