import FooterNav from '@/Components/common/FooterNav'
import ProductSiteNav from '@/Components/common/ProductSiteNav'
import WebsiteNav from '@/Components/common/WebsiteNav'
import FAQSection from '@/Components/home/FAQSection'
import HeroSection from '@/Components/home/HeroSection'
import HowItWorks from '@/Components/home/HowItWorks'
import WhyChoseUs from '@/Components/home/WhyChoseUs'
import Head from 'next/head'


export default function Home() {
  return (
    <>
      <Head>
        <title>UhuruChat</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="https://uhurutek.com/assets/img/favicon.png" />
      </Head>
      <main>
        <WebsiteNav />
        <ProductSiteNav />
        <HeroSection />
        <HowItWorks />
        <WhyChoseUs />
        <FAQSection />
        <FooterNav />
      </main>
    </>
  )
}
